package Shapes.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Color;
import java.awt.Dimension;

public class MyCanvas extends JFrame {
  private JPanel panel = new JPanel() {

    protected void paintComponent(Graphics graphics) {
      super.paintComponent(graphics);
      graphics.setColor(Color.red);
      graphics.drawOval(10, 20, 30, 30);
      graphics.setColor(Color.blue);
      graphics.drawRect(100, 200, 50, 50);
    }
  };

  public void initialize() {
    this.setTitle("MyCanvas");
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.add(panel);
    panel.setPreferredSize(new Dimension(600, 600));
    this.pack();
    this.setVisible(true);
  }

  public static void main(String[] args) {
    MyCanvas canvas = new MyCanvas();
    canvas.initialize();
  }
}
